version: '3.8'

services:
  test:
    build:
      context: .
      target: test
    command: npm test

  start-serverless:
    build:
      context: .
      target: serverless
    command: npm start
    ports:
      - "3000:3000"
